---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandacloud-app
  labels:
    app: pandacloud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pandacloud-app
  template:
    metadata:
      labels:
        app: pandacloud-app
    spec:
      containers:
      - name: pandacloud-container
        image: public.ecr.aws/p2j8v6t3/rakesh-poc:latest
        ports:
        - containerPort: 3000
...
